### ISSUE TITLE
Can't Access Che's Dashboard on localhost:8080

### ISSUE THREAD

**Issue by rrpolanco** [mickaelbaron/vagrant-dockereclipseche-ubuntu64-build#1]
I'm on Mac OS X 10.11.3 running Vagrant 1.8.1. 

Issued `vagrant up` and then `vagrant ssh -c /home/vagrant/eclipse-che-latest/eclipse*/bin/che.sh`. Went to http://www.localhost.com:8080 but could not load the app/dashboard...server not found. 

Am I missing something?

**Comment by mickaelbaron** [comment]
Hi,

> Issued vagrant up and then vagrant ssh -c /home/vagrant/eclipse-che-latest/eclipse*/bin/che.sh. Went to http://www.localhost.com:8080 but could not load the app/dashboard...server not found.

Euh ... can you remove both _www_ prefix and _.com_ suffix please. You need to use the local URL: localhost or 127.0.0.1

The right URL is: http://localhost:8080

Mickael

**Comment by rrpolanco** [comment]
_face palm_. Of course...Thank you for setting me straight.
